export * from "./dateComparator.test";
export * from "./dayOfWeek.test";
export * from "./deletePassword.test";
export * from "./extractItemByProperty.test";
export * from "./myCalendar.test";
export * from "./myCalendar.test";
export * from "./sortedCourses.test";
export * from "./sortedTechnicians.test";
export * from "./uniqueKey.test";
