export const valores = [
  {
    name: "Miguel Rodríguez",
    shortName: "MIGUEL",
    boolean1: false,
    boolean2: false,
    boolean3: true,
    boolean4: true,
    boolean5: true,
    boolean6: true,
    boolean7: true,
    boolean8: true,
  },
  {
    name: "Josep Hernández",
    shortName: "JOSEP",
    boolean1: true,
    boolean2: true,
    boolean3: true,
    boolean4: false,
    boolean5: true,
    boolean6: true,
    boolean7: false,
    boolean8: false,
  },
  {
    name: "Pilar González",
    shortName: "PILI",
    boolean1: true,
    boolean2: true,
    boolean3: true,
    boolean4: true,
    boolean5: true,
    boolean6: false,
    boolean7: true,
    boolean8: true,
  },
  {
    name: "Miguel Ángel Galindo",
    shortName: "M ÁNGEL",
    boolean1: false,
    boolean2: false,
    boolean3: true,
    boolean4: false,
    boolean5: true,
    boolean6: true,
    boolean7: false,
    boolean8: true,
  },
  {
    name: "Roser Feliu",
    shortName: "ROSER",
    boolean1: true,
    boolean2: true,
    boolean3: false,
    boolean4: true,
    boolean5: true,
    boolean6: true,
    boolean7: false,
    boolean8: false,
  },
];
